import psycopg2

def get_connection():
    try:
        return psycopg2.connect(
            database="postgres",
            user="postgres",
            password="root",
            host="127.0.0.1",
            port=5432,
        )
    except Exception as e:
        return e
#
# command = '''
#             CREATE TABLE url_handler (
#                 id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000000) PRIMARY KEY,
#                 user_URL VARCHAR(255) NOT NULL,
#                 short_Code VARCHAR(255),
#                 created_at timestamptz NOT NULL DEFAULT now()
#             );
#         '''

# conn = get_connection()
# if conn:
#     print("Connection is Godd")
# else:
#     print("u failed bitch")

def add_url (url):
    sql = "INSERT INTO url_handler (user_url) VALUES (%s) RETURNING id;"
    base_id = None
    try:
        with get_connection() as conn:
            with conn.cursor() as curr:
                curr.execute(sql, (url,))
                rows = curr.fetchone()
                if rows:
                    base_id = rows[0]

                conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        return base_id

def add_short_code (val, base_id):
    sql = '''
            UPDATE url_handler
            SET short_Code = (%s)
            WHERE id = (%s)
        '''
    try:
        with get_connection() as conn:
            with conn.cursor() as curr:
                curr.execute(sql, (val, base_id,))
                conn.commit()
    except (Exception, psycopg2.DatabaseError) as e:
        print(e)

def check_code (code):
    sql = '''
            SELECT user_URL 
            FROM url_handler
            WHERE short_code = (%s)
        '''

    try:
        with get_connection() as conn:
            with conn.cursor() as curr:
                curr.execute(sql, (code, ))
                row = curr.fetchone()
                if row:
                    return row

                conn.commit()
    except (Exception, psycopg2.DatabaseError) as e:
        print(e)
    

        
# conn = get_connection()
# cur = conn.cursor()
# cur.execute(command)
# conn.commit()
# print(add_url('https://www.geeksforgeeks.org/python/fastapi-pydantic/'))

# def auto_generated_id ():
#     sql = "SELECT lastval();"
#     ids = []
#     try:
#         with get_connection() as conn:
#             with conn.cursor() as curr:
#                 curr.execute(sql)
#                 rows = curr.fetchall()
#                 for row in rows:
#                     ids.append(row)
#
#                 conn.commit()
#     except (Exception, psycopg2.DatabaseError) as error:
#         return error
#     finally:
#         return ids
#
# print(auto_generated_id())
'''
Reference Material:-
import psycopg2
from config import load_config


def insert_vendor(vendor_name):
    """ Insert a new vendor into the vendors table """

    sql = """INSERT INTO vendors(vendor_name)
             VALUES(%s) RETURNING vendor_id;"""

    vendor_id = None
    config = load_config()

    try:
        with  psycopg2.connect(**config) as conn:
            with  conn.cursor() as cur:
                # execute the INSERT statement
                cur.execute(sql, (vendor_name,))

                # get the generated id back
                rows = cur.fetchone()
                if rows:
                    vendor_id = rows[0]

                # commit the changes to the database
                conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        return vendor_id


if __name__ == '__main__':
    insert_vendor("3M Co.")
'''
